// Code generated by qtc from "template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template.qtpl:1
package internal

//line template.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template.qtpl:1
func StreamGenerateFunc(qw422016 *qt422016.Writer, data *structsConfig) {
//line template.qtpl:1
	qw422016.N().S(`// Code generated by xvv, DO NOT EDIT.
package `)
//line template.qtpl:2
	qw422016.E().S(data.PkgName)
//line template.qtpl:2
	qw422016.N().S(`

`)
//line template.qtpl:5
	structs := data.Structs

//line template.qtpl:6
	qw422016.N().S(`import (
    "errors"
    "fmt"
    "github.com/duchiporexia/goutils/xerr"
    "gorm.io/gorm"
)
`)
//line template.qtpl:13
	for i := 0; i < len(structs); i++ {
//line template.qtpl:15
		item := structs[i]
		structName := item.StructName
		fields := item.Fields

//line template.qtpl:18
		qw422016.N().S(`
`)
//line template.qtpl:20
		for i := 0; i < len(fields); i++ {
//line template.qtpl:22
			field := fields[i]
			fieldName := field.FieldName
			columnName := field.ColumnName

//line template.qtpl:25
			qw422016.N().S(`const (
	k`)
//line template.qtpl:27
			qw422016.E().S(structName)
//line template.qtpl:27
			qw422016.N().S(`Col`)
//line template.qtpl:27
			qw422016.E().S(fieldName)
//line template.qtpl:27
			qw422016.N().S(` = "`)
//line template.qtpl:27
			qw422016.E().S(columnName)
//line template.qtpl:27
			qw422016.N().S(`"
	k`)
//line template.qtpl:28
			qw422016.E().S(structName)
//line template.qtpl:28
			qw422016.N().S(`Col`)
//line template.qtpl:28
			qw422016.E().S(fieldName)
//line template.qtpl:28
			qw422016.N().S(`Eq = "`)
//line template.qtpl:28
			qw422016.E().S(columnName)
//line template.qtpl:28
			qw422016.N().S(` = ?"
)
`)
//line template.qtpl:30
		}
//line template.qtpl:30
		qw422016.N().S(`
func (t *`)
//line template.qtpl:32
		qw422016.E().S(structName)
//line template.qtpl:32
		qw422016.N().S(`) BeforeCreate(db *gorm.DB) (err error) {
	if t.Id != 0 {
		return
	}
	t.Id, _ = xgenid.LongID()
	return
}
`)
//line template.qtpl:39
	}
//line template.qtpl:39
	qw422016.N().S(`
`)
//line template.qtpl:41
}

//line template.qtpl:41
func WriteGenerateFunc(qq422016 qtio422016.Writer, data *structsConfig) {
//line template.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:41
	StreamGenerateFunc(qw422016, data)
//line template.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:41
}

//line template.qtpl:41
func GenerateFunc(data *structsConfig) string {
//line template.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:41
	WriteGenerateFunc(qb422016, data)
//line template.qtpl:41
	qs422016 := string(qb422016.B)
//line template.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:41
	return qs422016
//line template.qtpl:41
}
