// Code generated by xvv, DO NOT EDIT.
package tests

import (
	"github.com/duchiporexia/goutils/xgenid"
	"gorm.io/gorm"
)

const (
	kUserColId   = "id"
	kUserColIdEq = "id = ?"
)
const (
	kUserColName   = "user_name"
	kUserColNameEq = "user_name = ?"
)
const (
	kUserColAge   = "age"
	kUserColAgeEq = "age = ?"
)
const (
	kUserColCreateTime   = "create_time"
	kUserColCreateTimeEq = "create_time = ?"
)

func (t *User) BeforeCreate(db *gorm.DB) (err error) {
	if t.Id != 0 {
		return
	}
	t.Id, _ = xgenid.LongID()
	return
}

const (
	kDogColId   = "id"
	kDogColIdEq = "id = ?"
)
const (
	kDogColName   = "name"
	kDogColNameEq = "name = ?"
)
const (
	kDogColAge   = "age"
	kDogColAgeEq = "age = ?"
)

func (t *Dog) BeforeCreate(db *gorm.DB) (err error) {
	if t.Id != 0 {
		return
	}
	t.Id, _ = xgenid.LongID()
	return
}
