// Code generated by xvv, DO NOT EDIT.
// HandlerType: Create

package test

import (
	"sync"
	"time"

	"github.com/duchiporexia/goutils/batch_handler/test/dto"
)

type SCreateHvHandlerConfig struct {
	Do           func(params dto.DogPo) (*dto.Dog, error)
	Wait         time.Duration
	MaxBatchSize int
}

type SCreateHvHandler struct {
	Do           func(params dto.DogPo) (*dto.Dog, error)
	Wait         time.Duration
	MaxBatchSize int
	batch        *sCreateHvHandlerBatch
	m            sync.Mutex
}

func NewSCreateHvHandler(config SCreateHvHandlerConfig) *SCreateHvHandler {
	return &SCreateHvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
	}
}

func (s *SCreateHvHandler) Query(params dto.DogPo) (*dto.Dog, error) {
	return s.QueryFuture(params)()
}

func (s *SCreateHvHandler) QueryFuture(params dto.DogPo) func() (*dto.Dog, error) {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &sCreateHvHandlerBatch{done: make(chan struct{})}
	}
	singleFunc := s.batch.getSingleFunc(s, params)
	s.m.Unlock()
	return singleFunc
}

type sCreateHvHandlerBatch struct {
	paramsList   []dto.DogPo
	data         []*dto.Dog
	error        []error
	funcs        []func() (*dto.Dog, error)
	funcDoneList []chan struct{}
	closing      bool
	done         chan struct{}
}

func (s *sCreateHvHandlerBatch) getSingleFunc(handler *SCreateHvHandler, params dto.DogPo) func() (*dto.Dog, error) {
	pos := len(s.funcDoneList)
	funcDone := make(chan struct{})
	s.funcDoneList = append(s.funcDoneList, funcDone)
	s.data = append(s.data, nil)
	s.error = append(s.error, nil)

	singleFunc := func() (*dto.Dog, error) {
		<-s.done
		var item *dto.Dog
		var err error

		item, err = handler.Do(params)
		s.data[pos] = item
		s.error[pos] = err
		close(funcDone)

		return item, err
	}

	s.funcs = append(s.funcs, singleFunc)

	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			close(s.done)
		}
	}

	return singleFunc
}

func (s *sCreateHvHandlerBatch) waiting(handler *SCreateHvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	close(s.done)
}
