// Code generated by xvv, DO NOT EDIT.
// HandlerType: Delete

package test

import (
	"sync"
	"time"

	"github.com/duchiporexia/goutils/batch_handler/test/dto"
)

type SDeleteHpHvHandlerConfig struct {
	Do           func(key int, params dto.DogPo) (*dto.Dog, error)
	Wait         time.Duration
	MaxBatchSize int
}

type SDeleteHpHvHandler struct {
	Do           func(key int, params dto.DogPo) (*dto.Dog, error)
	Wait         time.Duration
	MaxBatchSize int
	batch        *sDeleteHpHvHandlerBatch
	m            sync.Mutex
}

func NewSDeleteHpHvHandler(config SDeleteHpHvHandlerConfig) *SDeleteHpHvHandler {
	return &SDeleteHpHvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
	}
}

func (s *SDeleteHpHvHandler) Query(key int, params dto.DogPo) (*dto.Dog, error) {
	return s.QueryFuture(key, params)()
}

func (s *SDeleteHpHvHandler) QueryFuture(key int, params dto.DogPo) func() (*dto.Dog, error) {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &sDeleteHpHvHandlerBatch{done: make(chan struct{})}
	}
	singleFunc := s.batch.getSingleFunc(s, key, params)
	s.m.Unlock()
	return singleFunc
}

type sDeleteHpHvHandlerBatch struct {
	keys         []int
	paramsList   []dto.DogPo
	data         []*dto.Dog
	error        []error
	funcs        []func() (*dto.Dog, error)
	funcDoneList []chan struct{}
	closing      bool
	done         chan struct{}
}

func (s *sDeleteHpHvHandlerBatch) getSingleFunc(handler *SDeleteHpHvHandler, key int, params dto.DogPo) func() (*dto.Dog, error) {
	for i, existingKey := range s.keys {
		if key == existingKey {
			pos := i
			return func() (*dto.Dog, error) {
				<-s.funcDoneList[pos]
				return s.data[pos], s.error[pos]
			}
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	funcDone := make(chan struct{})
	s.funcDoneList = append(s.funcDoneList, funcDone)
	s.data = append(s.data, nil)
	s.error = append(s.error, nil)

	singleFunc := func() (*dto.Dog, error) {
		<-s.done
		var item *dto.Dog
		var err error

		item, err = handler.Do(key, params)
		s.data[pos] = item
		s.error[pos] = err
		close(funcDone)

		return item, err
	}

	s.funcs = append(s.funcs, singleFunc)

	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			close(s.done)
		}
	}

	return singleFunc
}

func (s *sDeleteHpHvHandlerBatch) waiting(handler *SDeleteHpHvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	close(s.done)
}
