// Code generated by xvv, DO NOT EDIT.
// HandlerType: Delete

package test

import (
	"servicehub/common/batch_handler/test/dto"
	"sync"
	"time"
)

type SDeleteHpNvHandlerConfig struct {
	Do           func(key int, params dto.DogPo) error
	Wait         time.Duration
	MaxBatchSize int
}

type SDeleteHpNvHandler struct {
	Do           func(key int, params dto.DogPo) error
	Wait         time.Duration
	MaxBatchSize int
	batch        *sDeleteHpNvHandlerBatch
	m            sync.Mutex
}

func NewSDeleteHpNvHandler(config SDeleteHpNvHandlerConfig) *SDeleteHpNvHandler {
	return &SDeleteHpNvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
	}
}

func (s *SDeleteHpNvHandler) Query(key int, params dto.DogPo) error {
	return s.QueryFuture(key, params)()
}

func (s *SDeleteHpNvHandler) QueryFuture(key int, params dto.DogPo) func() error {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &sDeleteHpNvHandlerBatch{done: make(chan struct{})}
	}
	singleFunc := s.batch.getSingleFunc(s, key, params)
	s.m.Unlock()
	return singleFunc
}

type sDeleteHpNvHandlerBatch struct {
	keys         []int
	paramsList   []dto.DogPo
	error        []error
	funcs        []func() error
	funcDoneList []chan struct{}
	closing      bool
	done         chan struct{}
}

func (s *sDeleteHpNvHandlerBatch) getSingleFunc(handler *SDeleteHpNvHandler, key int, params dto.DogPo) func() error {
	for i, existingKey := range s.keys {
		if key == existingKey {
			pos := i
			return func() error {
				<-s.funcDoneList[pos]
				return s.error[pos]
			}
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	funcDone := make(chan struct{})
	s.funcDoneList = append(s.funcDoneList, funcDone)
	s.error = append(s.error, nil)

	singleFunc := func() error {
		<-s.done

		var err error

		err = handler.Do(key, params)
		s.error[pos] = err
		close(funcDone)

		return err
	}

	s.funcs = append(s.funcs, singleFunc)

	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			close(s.done)
		}
	}

	return singleFunc
}

func (s *sDeleteHpNvHandlerBatch) waiting(handler *SDeleteHpNvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	close(s.done)
}
