// Code generated by xvv, DO NOT EDIT.
// HandlerType: Delete

package test

import (
	"sync"
	"time"
)

type SDeleteNpNvHandlerConfig struct {
	Do           func(key int) error
	Wait         time.Duration
	MaxBatchSize int
}

type SDeleteNpNvHandler struct {
	Do           func(key int) error
	Wait         time.Duration
	MaxBatchSize int
	batch        *sDeleteNpNvHandlerBatch
	m            sync.Mutex
}

func NewSDeleteNpNvHandler(config SDeleteNpNvHandlerConfig) *SDeleteNpNvHandler {
	return &SDeleteNpNvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
	}
}

func (s *SDeleteNpNvHandler) Query(key int) error {
	return s.QueryFuture(key)()
}

func (s *SDeleteNpNvHandler) QueryFuture(key int) func() error {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &sDeleteNpNvHandlerBatch{done: make(chan struct{})}
	}
	singleFunc := s.batch.getSingleFunc(s, key)
	s.m.Unlock()
	return singleFunc
}

type sDeleteNpNvHandlerBatch struct {
	keys         []int
	error        []error
	funcs        []func() error
	funcDoneList []chan struct{}
	closing      bool
	done         chan struct{}
}

func (s *sDeleteNpNvHandlerBatch) getSingleFunc(handler *SDeleteNpNvHandler, key int) func() error {
	for i, existingKey := range s.keys {
		if key == existingKey {
			pos := i
			return func() error {
				<-s.funcDoneList[pos]
				return s.error[pos]
			}
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	funcDone := make(chan struct{})
	s.funcDoneList = append(s.funcDoneList, funcDone)
	s.error = append(s.error, nil)

	singleFunc := func() error {
		<-s.done

		var err error

		err = handler.Do(key)
		s.error[pos] = err
		close(funcDone)

		return err
	}

	s.funcs = append(s.funcs, singleFunc)

	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			close(s.done)
		}
	}

	return singleFunc
}

func (s *sDeleteNpNvHandlerBatch) waiting(handler *SDeleteNpNvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	close(s.done)
}
