// Code generated by xvv, DO NOT EDIT.
// HandlerType: Delete

package test

import (
	"servicehub/common/batch_handler/test/dto"
	"sync"
	"time"
)

type SDeleteNpHvHandlerConfig struct {
	Do           func(key int) (*dto.Dog, error)
	Wait         time.Duration
	MaxBatchSize int
}

type SDeleteNpHvHandler struct {
	Do           func(key int) (*dto.Dog, error)
	Wait         time.Duration
	MaxBatchSize int
	batch        *sDeleteNpHvHandlerBatch
	m            sync.Mutex
}

func NewSDeleteNpHvHandler(config SDeleteNpHvHandlerConfig) *SDeleteNpHvHandler {
	return &SDeleteNpHvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
	}
}

func (s *SDeleteNpHvHandler) Query(key int) (*dto.Dog, error) {
	return s.QueryFuture(key)()
}

func (s *SDeleteNpHvHandler) QueryFuture(key int) func() (*dto.Dog, error) {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &sDeleteNpHvHandlerBatch{done: make(chan struct{})}
	}
	singleFunc := s.batch.getSingleFunc(s, key)
	s.m.Unlock()
	return singleFunc
}

type sDeleteNpHvHandlerBatch struct {
	keys         []int
	data         []*dto.Dog
	error        []error
	funcs        []func() (*dto.Dog, error)
	funcDoneList []chan struct{}
	closing      bool
	done         chan struct{}
}

func (s *sDeleteNpHvHandlerBatch) getSingleFunc(handler *SDeleteNpHvHandler, key int) func() (*dto.Dog, error) {
	for i, existingKey := range s.keys {
		if key == existingKey {
			pos := i
			return func() (*dto.Dog, error) {
				<-s.funcDoneList[pos]
				return s.data[pos], s.error[pos]
			}
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	funcDone := make(chan struct{})
	s.funcDoneList = append(s.funcDoneList, funcDone)
	s.data = append(s.data, nil)
	s.error = append(s.error, nil)

	singleFunc := func() (*dto.Dog, error) {
		<-s.done
		var item *dto.Dog
		var err error

		item, err = handler.Do(key)
		s.data[pos] = item
		s.error[pos] = err
		close(funcDone)

		return item, err
	}

	s.funcs = append(s.funcs, singleFunc)

	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			close(s.done)
		}
	}

	return singleFunc
}

func (s *sDeleteNpHvHandlerBatch) waiting(handler *SDeleteNpHvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	close(s.done)
}
