// Code generated by xvv, DO NOT EDIT.
// HandlerType: Read

package test

import (
	"servicehub/common/batch_handler/test/dto"
	"sync"
	"time"
)

type SReadHpHandlerConfig struct {
	Do           func(key string, params dto.DogPo) (*dto.Dog, error)
	Wait         time.Duration
	MaxBatchSize int
	CacheGet     func(key string) (*dto.Dog, error)
	CacheSet     func(key string, items *dto.Dog) error
}

type SReadHpHandler struct {
	Do           func(key string, params dto.DogPo) (*dto.Dog, error)
	Wait         time.Duration
	MaxBatchSize int
	CacheGet     func(key string) (*dto.Dog, error)
	CacheSet     func(key string, items *dto.Dog) error
	batch        *sReadHpHandlerBatch
	m            sync.Mutex
}

func NewSReadHpHandler(config SReadHpHandlerConfig) *SReadHpHandler {
	return &SReadHpHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
		CacheGet:     config.CacheGet,
		CacheSet:     config.CacheSet,
	}
}

func (s *SReadHpHandler) Query(key string, params dto.DogPo) (*dto.Dog, error) {
	return s.QueryFuture(key, params)()
}

func (s *SReadHpHandler) QueryFuture(key string, params dto.DogPo) func() (*dto.Dog, error) {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &sReadHpHandlerBatch{done: make(chan struct{})}
	}
	singleFunc := s.batch.getSingleFunc(s, key, params)
	s.m.Unlock()
	return singleFunc
}

type sReadHpHandlerBatch struct {
	keys         []string
	paramsList   []dto.DogPo
	data         []*dto.Dog
	error        []error
	funcs        []func() (*dto.Dog, error)
	funcDoneList []chan struct{}
	closing      bool
	done         chan struct{}
}

func (s *sReadHpHandlerBatch) getSingleFunc(handler *SReadHpHandler, key string, params dto.DogPo) func() (*dto.Dog, error) {
	for i, existingKey := range s.keys {
		if key == existingKey {
			pos := i
			return func() (*dto.Dog, error) {
				<-s.funcDoneList[pos]
				return s.data[pos], s.error[pos]
			}
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	funcDone := make(chan struct{})
	s.funcDoneList = append(s.funcDoneList, funcDone)
	s.data = append(s.data, nil)
	s.error = append(s.error, nil)

	singleFunc := func() (*dto.Dog, error) {
		<-s.done
		var item *dto.Dog
		var err error

		fromCache := false
		if handler.CacheGet != nil {
			if item, err = handler.CacheGet(key); err == nil {
				fromCache = true
			}
		}
		if !fromCache {
			item, err = handler.Do(key, params)
		}
		s.data[pos] = item
		s.error[pos] = err
		close(funcDone)

		if !fromCache && err == nil && handler.CacheSet != nil {
			_ = handler.CacheSet(key, item)
		}
		return item, err
	}

	s.funcs = append(s.funcs, singleFunc)

	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			close(s.done)
		}
	}

	return singleFunc
}

func (s *sReadHpHandlerBatch) waiting(handler *SReadHpHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	close(s.done)
}
