// Code generated by xvv, DO NOT EDIT.
// HandlerType: Update

package test

import (
	"sync"
	"time"

	"github.com/duchiporexia/goutils/batch_handler/test/dto"
)

type SUpdateHpNvHandlerConfig struct {
	Do           func(key int, params dto.DogPo) error
	Wait         time.Duration
	MaxBatchSize int
	CacheDel     func(keys ...int) error
}

type SUpdateHpNvHandler struct {
	Do           func(key int, params dto.DogPo) error
	Wait         time.Duration
	MaxBatchSize int
	CacheDel     func(keys ...int) error
	batch        *sUpdateHpNvHandlerBatch
	m            sync.Mutex
}

func NewSUpdateHpNvHandler(config SUpdateHpNvHandlerConfig) *SUpdateHpNvHandler {
	return &SUpdateHpNvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
		CacheDel:     config.CacheDel,
	}
}

func (s *SUpdateHpNvHandler) Query(key int, params dto.DogPo) error {
	return s.QueryFuture(key, params)()
}

func (s *SUpdateHpNvHandler) QueryFuture(key int, params dto.DogPo) func() error {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &sUpdateHpNvHandlerBatch{done: make(chan struct{})}
	}
	singleFunc := s.batch.getSingleFunc(s, key, params)
	s.m.Unlock()
	return singleFunc
}

type sUpdateHpNvHandlerBatch struct {
	keys         []int
	paramsList   []dto.DogPo
	error        []error
	funcs        []func() error
	funcDoneList []chan struct{}
	closing      bool
	done         chan struct{}
}

func (s *sUpdateHpNvHandlerBatch) getSingleFunc(handler *SUpdateHpNvHandler, key int, params dto.DogPo) func() error {
	for i, existingKey := range s.keys {
		if key == existingKey {
			pos := i
			return func() error {
				<-s.funcDoneList[pos]
				return s.error[pos]
			}
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	funcDone := make(chan struct{})
	s.funcDoneList = append(s.funcDoneList, funcDone)
	s.error = append(s.error, nil)

	singleFunc := func() error {
		<-s.done

		var err error

		err = handler.Do(key, params)
		s.error[pos] = err
		close(funcDone)

		if handler.CacheDel != nil {
			_ = handler.CacheDel(key)
		}
		return err
	}

	s.funcs = append(s.funcs, singleFunc)

	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			close(s.done)
		}
	}

	return singleFunc
}

func (s *sUpdateHpNvHandlerBatch) waiting(handler *SUpdateHpNvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	close(s.done)
}
