// Code generated by xvv, DO NOT EDIT.
// HandlerType: Delete

package test

import (
	"sync"
	"time"

	"github.com/duchiporexia/goutils/batch_handler/test/dto"
)

type TDeleteNpHvHandlerConfig struct {
	Do           func(keys []int) ([]*dto.Dog, []error)
	Wait         time.Duration
	MaxBatchSize int
}

type TDeleteNpHvHandler struct {
	Do           func(keys []int) ([]*dto.Dog, []error)
	Wait         time.Duration
	MaxBatchSize int
	batch        *tDeleteNpHvHandlerBatch
	m            sync.Mutex
}

func NewTDeleteNpHvHandler(config TDeleteNpHvHandlerConfig) *TDeleteNpHvHandler {
	return &TDeleteNpHvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
	}
}

func (s *TDeleteNpHvHandler) Query(key int) (*dto.Dog, error) {
	return s.QueryFuture(key)()
}

func (s *TDeleteNpHvHandler) QueryFuture(key int) func() (*dto.Dog, error) {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &tDeleteNpHvHandlerBatch{done: make(chan struct{})}
	}
	batch := s.batch
	pos := batch.getPosition(s, key)
	s.m.Unlock()

	return func() (*dto.Dog, error) {
		<-batch.done
		var data *dto.Dog
		if pos < len(batch.data) {
			data = batch.data[pos]
		}
		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		return data, err
	}
}

func (s *TDeleteNpHvHandler) QueryAll(keys []int) ([]*dto.Dog, []error) {
	return s.QueryAllFuture(keys)()
}

func (s *TDeleteNpHvHandler) QueryAllFuture(keys []int) func() ([]*dto.Dog, []error) {
	thunks := make([]func() (*dto.Dog, error), len(keys))
	for i, item := range keys {
		thunks[i] = s.QueryFuture(item)
	}

	return func() ([]*dto.Dog, []error) {
		errors := make([]error, len(keys))
		results := make([]*dto.Dog, len(keys))
		for i, thunk := range thunks {
			results[i], errors[i] = thunk()
		}
		return results, errors
	}
}

type tDeleteNpHvHandlerBatch struct {
	keys    []int
	data    []*dto.Dog
	error   []error
	closing bool
	done    chan struct{}
}

func (s *tDeleteNpHvHandlerBatch) getPosition(handler *TDeleteNpHvHandler, key int) int {
	for i, existingKey := range s.keys {
		if key == existingKey {
			return i
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			go s.finish(handler)
		}
	}

	return pos
}

func (s *tDeleteNpHvHandlerBatch) waiting(handler *TDeleteNpHvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	s.finish(handler)
}

func (s *tDeleteNpHvHandlerBatch) finish(handler *TDeleteNpHvHandler) {
	s.data, s.error = handler.Do(s.keys)
	close(s.done)

}
