// Code generated by xvv, DO NOT EDIT.
// HandlerType: Delete

package test

import (
	"servicehub/common/batch_handler/test/dto"
	"sync"
	"time"
)

type TDeleteHpNvHandlerConfig struct {
	Do           func(keys []int, paramsList []dto.DogPo) []error
	Wait         time.Duration
	MaxBatchSize int
}

type TDeleteHpNvHandler struct {
	Do           func(keys []int, paramsList []dto.DogPo) []error
	Wait         time.Duration
	MaxBatchSize int
	batch        *tDeleteHpNvHandlerBatch
	m            sync.Mutex
}

func NewTDeleteHpNvHandler(config TDeleteHpNvHandlerConfig) *TDeleteHpNvHandler {
	return &TDeleteHpNvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
	}
}

func (s *TDeleteHpNvHandler) Query(key int, params dto.DogPo) error {
	return s.QueryFuture(key, params)()
}

func (s *TDeleteHpNvHandler) QueryFuture(key int, params dto.DogPo) func() error {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &tDeleteHpNvHandlerBatch{done: make(chan struct{})}
	}
	batch := s.batch
	pos := batch.getPosition(s, key, params)
	s.m.Unlock()

	return func() error {
		<-batch.done
		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		return err
	}
}

func (s *TDeleteHpNvHandler) QueryAll(keys []int, paramsList []dto.DogPo) []error {
	return s.QueryAllFuture(keys, paramsList)()
}

func (s *TDeleteHpNvHandler) QueryAllFuture(keys []int, paramsList []dto.DogPo) func() []error {
	thunks := make([]func() error, len(keys))
	for i, item := range keys {
		thunks[i] = s.QueryFuture(item, paramsList[i])
	}

	return func() []error {
		errors := make([]error, len(keys))
		for i, thunk := range thunks {
			errors[i] = thunk()
		}
		return errors
	}
}

type tDeleteHpNvHandlerBatch struct {
	keys       []int
	paramsList []dto.DogPo
	error      []error
	closing    bool
	done       chan struct{}
}

func (s *tDeleteHpNvHandlerBatch) getPosition(handler *TDeleteHpNvHandler, key int, params dto.DogPo) int {
	for i, existingKey := range s.keys {
		if key == existingKey {
			return i
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	s.paramsList = append(s.paramsList, params)
	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			go s.finish(handler)
		}
	}

	return pos
}

func (s *tDeleteHpNvHandlerBatch) waiting(handler *TDeleteHpNvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	s.finish(handler)
}

func (s *tDeleteHpNvHandlerBatch) finish(handler *TDeleteHpNvHandler) {
	s.error = handler.Do(s.keys, s.paramsList)
	close(s.done)

}
