// Code generated by xvv, DO NOT EDIT.
// HandlerType: Update

package test

import (
	"sync"
	"time"
)

type TUpdateNpNvHandlerConfig struct {
	Do           func(keys []int) []error
	Wait         time.Duration
	MaxBatchSize int
	CacheDel     func(keys ...int) error
}

type TUpdateNpNvHandler struct {
	Do           func(keys []int) []error
	Wait         time.Duration
	MaxBatchSize int
	CacheDel     func(keys ...int) error
	batch        *tUpdateNpNvHandlerBatch
	m            sync.Mutex
}

func NewTUpdateNpNvHandler(config TUpdateNpNvHandlerConfig) *TUpdateNpNvHandler {
	return &TUpdateNpNvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
		CacheDel:     config.CacheDel,
	}
}

func (s *TUpdateNpNvHandler) Query(key int) error {
	return s.QueryFuture(key)()
}

func (s *TUpdateNpNvHandler) QueryFuture(key int) func() error {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &tUpdateNpNvHandlerBatch{done: make(chan struct{})}
	}
	batch := s.batch
	pos := batch.getPosition(s, key)
	s.m.Unlock()

	return func() error {
		<-batch.done
		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		return err
	}
}

func (s *TUpdateNpNvHandler) QueryAll(keys []int) []error {
	return s.QueryAllFuture(keys)()
}

func (s *TUpdateNpNvHandler) QueryAllFuture(keys []int) func() []error {
	thunks := make([]func() error, len(keys))
	for i, item := range keys {
		thunks[i] = s.QueryFuture(item)
	}

	return func() []error {
		errors := make([]error, len(keys))
		for i, thunk := range thunks {
			errors[i] = thunk()
		}
		return errors
	}
}

type tUpdateNpNvHandlerBatch struct {
	keys    []int
	error   []error
	closing bool
	done    chan struct{}
}

func (s *tUpdateNpNvHandlerBatch) getPosition(handler *TUpdateNpNvHandler, key int) int {
	for i, existingKey := range s.keys {
		if key == existingKey {
			return i
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			go s.finish(handler)
		}
	}

	return pos
}

func (s *tUpdateNpNvHandlerBatch) waiting(handler *TUpdateNpNvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	s.finish(handler)
}

func (s *tUpdateNpNvHandlerBatch) finish(handler *TUpdateNpNvHandler) {
	s.error = handler.Do(s.keys)
	close(s.done)

	if handler.CacheDel != nil {
		_ = handler.CacheDel(s.keys...)
	}
}
