// Code generated by xvv, DO NOT EDIT.
// HandlerType: Update

package test

import (
	"sync"
	"time"

	"github.com/duchiporexia/goutils/batch_handler/test/dto"
)

type TUpdateHpNvHandlerConfig struct {
	Do           func(keys []int, paramsList []dto.DogPo) []error
	Wait         time.Duration
	MaxBatchSize int
	CacheDel     func(keys ...int) error
}

type TUpdateHpNvHandler struct {
	Do           func(keys []int, paramsList []dto.DogPo) []error
	Wait         time.Duration
	MaxBatchSize int
	CacheDel     func(keys ...int) error
	batch        *tUpdateHpNvHandlerBatch
	m            sync.Mutex
}

func NewTUpdateHpNvHandler(config TUpdateHpNvHandlerConfig) *TUpdateHpNvHandler {
	return &TUpdateHpNvHandler{
		Do:           config.Do,
		Wait:         config.Wait,
		MaxBatchSize: config.MaxBatchSize,
		CacheDel:     config.CacheDel,
	}
}

func (s *TUpdateHpNvHandler) Query(key int, params dto.DogPo) error {
	return s.QueryFuture(key, params)()
}

func (s *TUpdateHpNvHandler) QueryFuture(key int, params dto.DogPo) func() error {
	s.m.Lock()
	if s.batch == nil {
		s.batch = &tUpdateHpNvHandlerBatch{done: make(chan struct{})}
	}
	batch := s.batch
	pos := batch.getPosition(s, key, params)
	s.m.Unlock()

	return func() error {
		<-batch.done
		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		return err
	}
}

func (s *TUpdateHpNvHandler) QueryAll(keys []int, paramsList []dto.DogPo) []error {
	return s.QueryAllFuture(keys, paramsList)()
}

func (s *TUpdateHpNvHandler) QueryAllFuture(keys []int, paramsList []dto.DogPo) func() []error {
	thunks := make([]func() error, len(keys))
	for i, item := range keys {
		thunks[i] = s.QueryFuture(item, paramsList[i])
	}

	return func() []error {
		errors := make([]error, len(keys))
		for i, thunk := range thunks {
			errors[i] = thunk()
		}
		return errors
	}
}

type tUpdateHpNvHandlerBatch struct {
	keys       []int
	paramsList []dto.DogPo
	error      []error
	closing    bool
	done       chan struct{}
}

func (s *tUpdateHpNvHandlerBatch) getPosition(handler *TUpdateHpNvHandler, key int, params dto.DogPo) int {
	for i, existingKey := range s.keys {
		if key == existingKey {
			return i
		}
	}
	pos := len(s.keys)
	s.keys = append(s.keys, key)
	s.paramsList = append(s.paramsList, params)
	if pos == 0 {
		go s.waiting(handler)
	}

	if handler.MaxBatchSize != 0 && pos >= handler.MaxBatchSize-1 {
		if !s.closing {
			s.closing = true
			handler.batch = nil
			go s.finish(handler)
		}
	}

	return pos
}

func (s *tUpdateHpNvHandlerBatch) waiting(handler *TUpdateHpNvHandler) {
	time.Sleep(handler.Wait)
	handler.m.Lock()
	if s.closing {
		handler.m.Unlock()
		return
	}
	handler.batch = nil
	handler.m.Unlock()

	s.finish(handler)
}

func (s *tUpdateHpNvHandlerBatch) finish(handler *TUpdateHpNvHandler) {
	s.error = handler.Do(s.keys, s.paramsList)
	close(s.done)

	if handler.CacheDel != nil {
		_ = handler.CacheDel(s.keys...)
	}
}
